import { eq } from "drizzle-orm";
import { Octokit } from "octokit";
import { getDb } from "@/db";
import { projects, sessions } from "@/db/schema";
import { getSessionFiles } from "@/server/files";

// ---------------------------------------------------------------------------
// Phase 3 (Half B, gated inert): GitHub "Save" — wired against Octokit's
// real, documented REST API. PLAN.md originally called for a GitHub App;
// registering one needs manual GitHub-side console setup this environment
// can't automate, so this is a deliberate simplification: a single
// personal-access-token-style GITHUB_TOKEN env var, same "off by default,
// gated inert" pattern as Clerk (src/lib/auth.ts) and MOCK_AGENT before it.
//
// Code-complete against Octokit's current API, NOT live-verified — no real
// GITHUB_TOKEN exists in this environment.
// ---------------------------------------------------------------------------

export function isGitHubConfigured(): boolean {
  return Boolean(process.env.GITHUB_TOKEN);
}

function getOctokit(): Octokit {
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

async function getSessionWithProject(sessionId: string) {
  const db = getDb();
  const [row] = await db
    .select({ session: sessions, project: projects })
    .from(sessions)
    .innerJoin(projects, eq(sessions.projectId, projects.id))
    .where(eq(sessions.id, sessionId));
  return row ?? null;
}

function statusOf(err: unknown): number | undefined {
  return typeof err === "object" && err !== null && "status" in err
    ? (err as { status?: number }).status
    : undefined;
}

/**
 * Pushes a session's current `files` snapshot to a GitHub repo via Octokit —
 * creates the repo (named after the project slug) on first save, reuses it
 * (by the session's stored `githubRepoUrl`, or by looking the name up again
 * if that repo already existed) on subsequent saves. One
 * createOrUpdateFileContents call per file — simplest correct approach for
 * this phase's file counts; not a Git-tree/batch commit.
 */
export async function saveSessionToGitHub(sessionId: string): Promise<{ url: string }> {
  if (!isGitHubConfigured()) {
    throw new Error("GITHUB_TOKEN is not configured");
  }

  const row = await getSessionWithProject(sessionId);
  if (!row) {
    throw new Error("Session not found");
  }

  const files = await getSessionFiles(sessionId);
  if (files.length === 0) {
    throw new Error("Nothing to save yet — no files have been built for this session");
  }

  const octokit = getOctokit();
  const { data: authUser } = await octokit.rest.users.getAuthenticated();
  const owner = authUser.login;
  const repoName = row.project.slug;

  let repoUrl: string;
  if (row.session.githubRepoUrl) {
    repoUrl = row.session.githubRepoUrl;
  } else {
    try {
      const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        private: true,
        description: `Generated by Emergent clone — project ${row.project.slug}`,
      });
      repoUrl = repo.html_url;
    } catch (err) {
      // 422 = a repo with this name already exists under this account —
      // reuse it rather than failing the save.
      if (statusOf(err) === 422) {
        const { data: repo } = await octokit.rest.repos.get({ owner, repo: repoName });
        repoUrl = repo.html_url;
      } else {
        throw err;
      }
    }
  }

  for (const file of files) {
    let sha: string | undefined;
    try {
      const { data: existing } = await octokit.rest.repos.getContent({
        owner,
        repo: repoName,
        path: file.path,
      });
      if (!Array.isArray(existing) && existing.type === "file") {
        sha = existing.sha;
      }
    } catch (err) {
      if (statusOf(err) !== 404) throw err;
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo: repoName,
      path: file.path,
      message: sha ? `Update ${file.path}` : `Add ${file.path}`,
      content: Buffer.from(file.content, "utf8").toString("base64"),
      sha,
    });
  }

  const db = getDb();
  await db.update(sessions).set({ githubRepoUrl: repoUrl }).where(eq(sessions.id, sessionId));

  return { url: repoUrl };
}
